Repository v-community/v_by_example, pull requests merged in 2019-10, with the labels that each got.

#12 ignore executable
  .gitignore
Labels: chores

#14 Primitives, Variables, Operators and Mutability
  .gitignore
  README.md
  src/hello_world/README.md
  src/hello_world/code/hello.v
  src/hello_world/hello.md
  src/keywords.md
  src/operator.md
  src/primitives/primitives.md
Labels: WIP, enhancement

#15 Rename example path
  examples/hello_world/code/hello.v
  examples/hello_world/hello.md
  examples/keywords.md
  examples/operator.md
  examples/primitives/primitives.md
Labels: chores

#17 Update repo structure
  code/hello_world/hello.v
Labels: chores

#16 Fix Discord link
  README.md
Labels: documentation

#18 update primitives.md
  examples/primitives/primitives.md
Labels: chores

#19 example: conditional statements like if, else, else if, for and while.
  .gitignore
  examples/conditional_statements/conditional_statements.md
Labels: documentation, enhancement

#22 add description & change syntax highlighting from go to v on MD's
  README.md
  examples/conditional_statements/conditional_statements.md
  examples/hello_world/hello.md
  examples/operator.md
Labels: documentation

#20 example: functions, arrays, structures etc
  CHANGELOG.md
  README.md
  examples/arrays.md
  examples/conditional_statements/conditional_statements.md
  examples/functions.md
  examples/hello_world/hello.md
  examples/operator.md
  examples/struct.md
  october.plan
Labels: documentation, enhancement

#24 Minor fixes
  README.md
  examples/arrays.md
  examples/conditional_statements/conditional_statements.md
  examples/functions.md
  october.plan
Labels: chores

#31 Exponent typo
  examples/primitives/primitives.md
Labels: bug

#32 More typos
  examples/primitives/primitives.md
Labels: bug

#26 [WIP] Follow #25 and more progress
  README.md
  examples/arrays/arrays.md
  examples/arrays/functions.md
  examples/conditional_statements/conditional_statements.md
  examples/functions/functions.md
  examples/hello_world/comment.md
  examples/hello_world/hello.md
  examples/keywords.md
  examples/loops/loops.md
  examples/operator.md
  examples/struct/struct.md
Labels: enhancement

#37 Fix broken README links
  README.md
Labels: documentation

#38 Improve contributing
  CONTRIBUTING.md
Labels: documentation

#40 November and December plan
  november+december.plan
  october.plan
Labels: documentation
