Repository v-community/v_by_example, pull requests merged in 2019-12, with the labels that each got.

#91 Add string examples
  .typo-ci.yml
  README.md
  examples/strings/strings.md
  november+december.plan
Labels: documentation

#90 Update .plan
  november+december.plan
Labels: documentation

#97 add documentation style guide
  docs_style_guide.md
Labels: documentation

#75 example: reading and writing files
  .typo-ci.yml
  README.md
  examples/files/files.md
Labels: enhancement

#98 Fix conditional statement broken link in readme
  README.md
Labels: bug

#100 change syntax highlighting back to Go & do some changes
  .typo-ci.yml
  examples/arrays/arrays.md
  examples/arrays/functions.md
  examples/conditional_statements/if-else.md
  examples/files/files.md
  examples/functions/functions.md
  examples/hello_world/comment.md
  examples/hello_world/hello.md
  examples/json.md
  examples/loops/loops.md
  examples/methods/methods.md
  examples/strings/strings.md
  examples/struct/struct.md
  examples/testing.md
  examples/variables/variables.md
Labels: enhancement

#101 Reorganize files in examples folder
  README.md
  examples/array-functions.md
  examples/arrays.md
  examples/comment.md
  examples/files.md
  examples/functions.md
  examples/hello.md
  examples/if-else.md
  examples/loops.md
  examples/match.md
  examples/methods.md
  examples/primitives.md
  examples/strings.md
  examples/struct.md
  examples/variables.md
Labels: chores

#103 array: slice
  .gitignore
  examples/arrays.md
Labels: documentation

#104 Add sections structure to readme
  README.md
  examples/section_1/hello_world.md
  examples/section_1/keywords.md
  examples/section_1/primitives.md
  examples/section_1/strings.md
  examples/section_1/variables.md
  examples/section_2/if-else.md
  examples/section_2/loops.md
  examples/section_2/match.md
  examples/section_2/operator.md
  examples/section_3/arrays.md
  examples/section_3/functions.md
  examples/section_3/methods.md
  examples/section_3/struct.md
  examples/section_4/array-functions.md
  examples/section_4/files.md
  examples/section_4/json.md
  examples/section_4/testing.md
  examples/section_5/comment.md
Labels: documentation

#105 Explain sections
  README.md
  examples/section_1/comment.md
Labels: documentation

#106 Add maintainers to readme
  README.md
Labels: documentation

#107 Translate comment example to portuguese
  README.md
  README_pt-br.md
  examples/en/section_1/comment.md
  examples/en/section_1/hello_world.md
  examples/en/section_1/keywords.md
  examples/en/section_1/primitives.md
  examples/en/section_1/strings.md
  examples/en/section_1/variables.md
  examples/en/section_2/if-else.md
  examples/en/section_2/loops.md
  examples/en/section_2/match.md
  examples/en/section_2/operator.md
  examples/en/section_3/arrays.md
  examples/en/section_3/functions.md
  examples/en/section_3/methods.md
  examples/en/section_3/struct.md
  examples/en/section_4/array-functions.md
  examples/en/section_4/files.md
  examples/en/section_4/json.md
  examples/en/section_4/testing.md
  examples/pt-br/section_1/comment.md
Labels: enhancement

#108 Restructure language folders
  CONTRIBUTING_pt-br.md
  README.md
  README_pt-br.md
  en/examples/section_1/comment.md
  en/examples/section_1/hello_world.md
  en/examples/section_1/keywords.md
  en/examples/section_1/primitives.md
  en/examples/section_1/strings.md
  en/examples/section_1/variables.md
  en/examples/section_2/if-else.md
  en/examples/section_2/loops.md
  en/examples/section_2/match.md
  en/examples/section_2/operator.md
  en/examples/section_3/arrays.md
  en/examples/section_3/functions.md
  en/examples/section_3/methods.md
  en/examples/section_3/struct.md
  en/examples/section_4/array-functions.md
  en/examples/section_4/files.md
  en/examples/section_4/json.md
  en/examples/section_4/testing.md
  pt-br/examples/section_1/comment.md
Labels: documentation

#109 Translate Operators to Brazilian Portuguese
  .typo-ci.yml
  README_pt-br.md
  pt-br/examples/section_2/operators.md
Labels: enhancement

#114 Fix readme_pt-br text
  .typo-ci.yml
  README_pt-br.md
Labels: documentation

#111 Translate keywords to Brazilian Portuguese
  .typo-ci.yml
  README_pt-br.md
  pt-br/examples/section_1/keywords.md
Labels: enhancement

#112 German V
  .typo-ci.yml
  README.md
  de/CONTRIBUTING_de.md
  de/README_de.md
  de/examples/section_1/comment.md
  de/examples/section_1/hello_world.md
  de/examples/section_1/keywords.md
  de/examples/section_1/primitives.md
  de/examples/section_1/strings.md
  de/examples/section_1/variables.md
  de/examples/section_2/if-else.md
  de/examples/section_2/loops.md
  de/examples/section_2/match.md
  de/examples/section_2/operator.md
  de/examples/section_3/arrays.md
  de/examples/section_3/functions.md
  de/examples/section_3/methods.md
  de/examples/section_3/struct.md
  de/examples/section_4/array-functions.md
  de/examples/section_4/files.md
  de/examples/section_4/json.md
  de/examples/section_4/testing.md
Labels: WIP, documentation, enhancement

#115 Translate primitives to Brazilian Portuguese
  .typo-ci.yml
  README_pt-br.md
  pt-br/examples/section_1/primitives.md
Labels: enhancement

#134 Change pt-br structure to match de structure
  README.md
  de/README_de.md
  pt-br/CONTRIBUTING_pt-br.md
  pt-br/README_pt-br.md
Labels: documentation

#144 Add January plan
  january.plan
Labels: documentation
